### ISSUE TITLE
Problem building on macOS v 10.12.2

### ISSUE THREAD

**Issue by bryongloden** [nccgroup/TriforceAFL#2]
Greetings,

We're following your instructions in TriforceAFL/docs/INSTALL, and we're getting an error. Have you got any suggestions for us? If it's any help, we're at about an advanced beginner level when it comes to answering any questions about our system configuration.

Bryons-MacBook-Pro:TriforceAFL bryongloden$ make
[*] Checking for the ability to compile x86 code...
[+] Everything seems to be working, ready to compile.
[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"2.06b\" test-instr.c -o test-instr 
echo 0 | ./afl-showmap -m none -q -o .test-instr0 -- ./test-instr
echo 1 | ./afl-showmap -m none -q -o .test-instr1 -- ./test-instr
[+] All right, the instrumentation seems to be working!
[+] All done! Be sure to review README - it's pretty short and useful.

WARNING: Fuzzing on MacOS X is slow because of the unusually high overhead of
fork() on this OS. Consider using Linux or *BSD. You can also use VirtualBox
(virtualbox.org) to put AFL inside a Linux or *BSD VM.

NOTE: If you can read this, your terminal probably uses white background.
This will make the UI hard to read. See docs/status_screen.txt for advice.
cd qemu_mode && ./build_qemu_support.sh

ERROR: User requested feature nptl
       configure was not able to find it.
       Install glibc and linux kernel headers.

Please call configure before running make!
make[1]: *** [config-host.mak] Error 1
cp: x86_64-linux-user/qemu-x86_64: No such file or directory
cp: x86_64-softmmu/qemu-system-x86_64: No such file or directory
make: *** [afl-qemu-system-trace] Error 1
Bryons-MacBook-Pro:TriforceAFL bryongloden$

**Comment by timnewsham** [comment]
We've never tried it in OS X. The officially supported platform is ubuntu.

Sent from my iPhone

On Jan 15, 2017, at 12:06 PM, Bryon Gloden, CISSP(r) <notifications@github.com<mailto:notifications@github.com>> wrote:


Greetings,

We're following your instructions in TriforceAFL/docs/INSTALL, and we're getting an error. Have you got any suggestions for us? If it's any help, we're at about an advanced beginner level when it comes to answering any questions about our system configuration.

Bryons-MacBook-Pro:TriforceAFL bryongloden$ make
[] Checking for the ability to compile x86 code...
[+] Everything seems to be working, ready to compile.
[] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-clang -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH="/usr/local/lib/afl" -DDOC_PATH="/usr/local/share/doc/afl" -DBIN_PATH="/usr/local/bin" -DVERSION="2.06b" test-instr.c -o test-instr
echo 0 | ./afl-showmap -m none -q -o .test-instr0 -- ./test-instr
echo 1 | ./afl-showmap -m none -q -o .test-instr1 -- ./test-instr
[+] All right, the instrumentation seems to be working!
[+] All done! Be sure to review README - it's pretty short and useful.

WARNING: Fuzzing on MacOS X is slow because of the unusually high overhead of
fork() on this OS. Consider using Linux or *BSD. You can also use VirtualBox
(virtualbox.org<http://virtualbox.org>) to put AFL inside a Linux or *BSD VM.

NOTE: If you can read this, your terminal probably uses white background.
This will make the UI hard to read. See docs/status_screen.txt for advice.
cd qemu_mode && ./build_qemu_support.sh

ERROR: User requested feature nptl
configure was not able to find it.
Install glibc and linux kernel headers.

Please call configure before running make!
make[1]: *** [config-host.mak] Error 1
cp: x86_64-linux-user/qemu-x86_64: No such file or directory
cp: x86_64-softmmu/qemu-system-x86_64: No such file or directory
make: *** [afl-qemu-system-trace] Error 1
Bryons-MacBook-Pro:TriforceAFL bryongloden$

-
